[package]
name = "f1-api"
version = "0.0.0"
edition = "2018"

authors = ["Jan David <jandavid@6a64.com>"]
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[example]]
name = "cli"

[dependencies]
bitflags = "1.2.1"
bytes = "0.5.4"
tokio-util = { version = "0.3.0", features = ["codec"] }

[dev-dependencies]
clap = "2.33.0"
