[package]
name = "f1-api"
version = "0.0.0"
edition = "2018"

authors = ["Jan David <jandavid@6a64.com>"]
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[example]]
name = "cli"

[dependencies]
bitflags = "1.2.1"
bytes = "0.5.4"
derive-new = "0.5.8"
getset = "0.1.0"
net2 = "0.2.33"
tokio = { version = "0.2.13", features = ["macros", "net", "stream", "udp"] }
tokio-util = { version = "0.3.0", features = ["codec", "udp"] }

[dev-dependencies]
clap = "2.33.0"
