name: release

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish crate to crates.io
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/cargo@v1
        with:
          command: publish
          args: -v --all-features
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}
